kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ name }}
  namespace: eessibasis
  labels:
    team: eessibasis
spec:
  image: {{ image }}
  ingresses:
    - {{ ingress }}
  liveness:
    path: /actuator/health
    port: 8080
    initialDelay: 40
    timeout: 90
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health
    port: 8080
    initialDelay: 40
    timeout: 90
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 800m
      memory: 512Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      replyURLs:
        - "{{ ingress }}/callback"
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/**
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    inbound:
      rules:
        - application: {{ application.eux-journalarkivar-feilregistrer-naisjob.name }}
          namespace: {{ application.eux-journalarkivar-feilregistrer-naisjob.namespace }}
          cluster: {{ cluster.gcp }}
        - application: {{ application.eux-journalarkivar-ferdigstill-naisjob.name }}
          namespace: {{ application.eux-journalarkivar-ferdigstill-naisjob.namespace }}
          cluster: {{ cluster.gcp }}
    outbound:
      external:
        - host: {{ application.saf.host }}
        - host: {{ application.dokarkiv.host }}
        - host: {{ application.eux-rina-api.host }}
      rules:
        - application: {{ application.eux-oppgave.name }}
        - application: {{ application.eux-journal.name }}
        - application: {{ application.eux-nav-rinasak.name }}
  env:
    - name: CLIENT_EUXNAVRINASAK_ENDPOINT
      value: {{ application.eux-nav-rinasak.endpoint }}
    - name: CLIENT_EUXNAVRINASAK_SCOPE
      value: {{ application.eux-nav-rinasak.scope }}

    - name: CLIENT_EUXOPPGAVE_ENDPOINT
      value: {{ application.eux-oppgave.endpoint }}
    - name: CLIENT_EUXOPPGAVE_SCOPE
      value: {{ application.eux-oppgave.scope }}

    - name: CLIENT_EUXJOURNAL_ENDPOINT
      value: {{ application.eux-journal.endpoint }}
    - name: CLIENT_EUXJOURNAL_SCOPE
      value: {{ application.eux-journal.scope }}

    - name: CLIENT_EUXRINAAPI_ENDPOINT
      value: {{ application.eux-rina-api.endpoint }}
    - name: CLIENT_EUXRINAAPI_SCOPE
      value: {{ application.eux-rina-api.scope }}

    - name: CLIENT_SAF_ENDPOINT
      value: {{ application.saf.endpoint }}
    - name: CLIENT_SAF_SCOPE
      value: {{ application.saf.scope }}

    - name: CLIENT_DOKARKIV_ENDPOINT
      value: {{ application.dokarkiv.endpoint }}
    - name: CLIENT_DOKARKIV_SCOPE
      value: {{ application.dokarkiv.scope }}
