openapi: 3.0.3
info:
  title: Eux Journalarkivar API
  description: Journalarkivar API for EUX
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v1
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Eux Journal API
    description: >-
        API for å utføre operasjoner på journalposter

paths:
  '/ferdigstillJournalposter':
    $ref: 'journalarkivar/operations_rot.yaml'
